name: CI

on:
  workflow_run:
    workflows: ["PR"]
    types:
      - completed


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - name: npm intsall
        run: npm i

      - name: lint
        run: npm run lint
