name: ci

on: pull_request

jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: '🚚 Checkout source code'
        uses: actions/checkout@v4
      - name: '📦 Cache dependencies'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: 'npm install'
        run: npm ci --prefer-offline --no-audit --no-fund
  unit-test:
    name: unit-tests
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: '📦 Cache dependencies'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: 'npm install'
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: 'Test Client'
        run: npm run test
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: '📦 Cache dependencies'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: 'npm install'
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: 'Lint'
        run: npm run lint
  build:
    name: build
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: '📦 Cache dependencies'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: 'npm install'
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: 'Build'
        run: npm run build
