name: ci

on: pull_request

jobs:
  unit-test:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: 'npm install'
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: 'Test Client'
        run: npm run test
