name: 'Post Merge'
on:
  push:
    branches:
      - master

jobs:
  write-info:
    runs-on: ubuntu-latest
    name: 'Write Info'
    steps:
      - uses: actions/checkout@v3
      - name: 'Get Info'
        run: |
          echo "shortCommit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "currentVersion=$(cat info.json | jq -r '.version')" >> $GITHUB_ENV
      - name: 'Calc Next Version'
        id: next-version
        shell: bash
        run: |
          split=(${VERSION//.// })
          index=$((${#split[@]}-1))
          nexPatchVersion=$((${split[$index]} + 1))
          echo nextVersion=${{format('{0}.{1}.{2}', '${split[0]/\//}', '${split[1]/\//}', '$nexPatchVersion')}} >> $GITHUB_ENV
        env:
          VERSION: ${{ env.currentVersion }}
      - name: 'Update Short Commit'
        uses: jossef/action-set-json-field@v2.1
        with:
          file: info.json
          field: shortCommit
          value: ${{ env.shortCommit }}
      - name: 'Update New Version'
        uses: jossef/action-set-json-field@v2.1
        with:
          file: info.json
          field: version
          value: ${{ env.nextVersion }}
      - name: 'Get Data from Github'
        run: |
          echo GITHUB_EMAIL=$(git --no-pager show -s --format=\'%ae\') >> $GITHUB_ENV
          echo GITHUB_COMMIT_MESSAGE=$(git log -1 --pretty=%B) >> $GITHUB_ENV
      - name: 'Setup GIT'
        run: |
          echo "Setting email to: ${GITHUB_EMAIL}"
          echo "Setting user to: ${GITHUB_ACTOR}"
          echo "Commit message: $GITHUB_COMMIT_MESSAGE"
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_ACTOR"
      - name: 'Push Info File'
        run: |
          git add -A
          git commit -m "docs(): bumping release v$VERSION"
          git push "https://$GITHUB_ACTOR@github.com/$GITHUB_REPOSITORY"
        env:
          VERSION: ${{ env.nextVersion }}
