name: Rebase PR

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'rebase pr')
    runs-on: ubuntu-latest

    steps:
      - name: 'Rebase PR'
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.VERSION_BUMP }}
          commands: rebase
          permission: write
          issue-type: pull-request
