name: Rebase PR

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'rebase pr')
    runs-on: ubuntu-latest

    steps:
      - name: 'Add a reaction (emoji) to the comment'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_ID=${{ github.event.comment.id }}
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/$COMMENT_ID/reactions \
            -d '{"content": "+1"}'

      - name: 'Slash Command Dispatch'
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.VERSION_BUMP }}
          commands: rebase
          permission: write
          issue-type: pull-request
