name: Rebase PR

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'rebase pr')
    runs-on: ubuntu-latest

    steps:
      - name: Add Emoji Reaction
        env:
          GH_TOKEN: ${{ secrets.VERSION_BUMP }}
        run: |
          COMMENT_ID=${{ github.event.comment.id }}
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/$COMMENT_ID/reactions \
            -d '{"content": "+1"}'

      - name: 'Fetch'
        run: git fetch origin

      - name: 'Rebase'
        run: |
          git rebase origin/master
          git push --force-with-lease
        env:
          GH_TOKEN: ${{ secrets.VERSION_BUMP }}
