name: Write Info to File
on:
  push:
    branches:
      - master

jobs:
  write-info:
    runs-on: ubuntu-latest
    name: Write Info
    steps:
      - uses: actions/checkout@v3
      - name: Get Info
        id: vars
        run: |
          echo ::set-output name=shortCommit::$(git rev-parse --short HEAD)
      - name: Update short commit
        uses: jossef/action-set-json-field@v2
        with:
          file: info.json
          field: shortCommit
          value: ${{ steps.vars.outputs.shortCommit }}
      - name: 'Setup GIT'
        run: |
          echo "Setting email to: ${GITHUB_EMAIL}"
          echo "Setting user to: ${GITHUB_ACTOR}"
          echo "Commit message: $GITHUB_COMMIT_MESSAGE"
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_ACTOR"
      - name: 'Push version'
        run: |
          git add -A
          git commit -m "docs(): bumping release $SHORT_COMMIT"
          git push "https://$GITHUB_ACTOR@github.com/$GITHUB_REPOSITORY"
        env:
          SHORT_COMMIT: ${{ steps.vars.outputs.shortCommit }}
