name: Upgrade Version
on: pull_request

jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'info.json'
          version-regexp: '\d+.\d+.\d+'
