name: Write Version to File
on:
  push:
    branches:
      - master

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
      - uses: actions/checkout@master
      - name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: '.version'
          placeholder: '${VERSION}'
      - name: 'Setup GIT'
        run: |
          echo "Setting email to: ${GITHUB_EMAIL}"
          echo "Setting user to: ${GITHUB_ACTOR}"
          echo "Commit message: $GITHUB_COMMIT_MESSAGE"
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_ACTOR"
      - name: 'Push version'
        run: |
          git add .version
          git push "https://$GITHUB_ACTOR@github.com/$GITHUB_REPOSITORY"
