name: Write Version to File
on:
  push:
    branches:
      - master

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: vars
        run: echo ::set-output name=version::$(cat info.json | jq -r '.version')
      - name: Calc next version
        id: next-version
        shell: bash
        run: |
          split=(${VERSION//.// })
          index=$((${#split[@]}-1))
          PATCH_VERSION=${split[$index]}
          echo PATCH_VERSION=$PATCH_VERSION + 1 >> $GITHUB_ENV
          echo "::set-output name=PATCH_VERSION::$PATCH_VERSION"
        env:
          VERSION: ${{ steps.vars.outputs.version }}
      - name: Update Version
        uses: jossef/action-set-json-field@v2
        with:
          file: info.json
          field: version
          value: ${{ steps.next-version.outputs.version }}
      - name: 'Setup GIT'
        run: |
          echo "Setting email to: ${GITHUB_EMAIL}"
          echo "Setting user to: ${GITHUB_ACTOR}"
          echo "Commit message: $GITHUB_COMMIT_MESSAGE"
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_ACTOR"
      - name: 'Push version'
        run: |
          git add -A
          git commit -m "docs(): bumping release $VERSION"
          git push "https://$GITHUB_ACTOR@github.com/$GITHUB_REPOSITORY"
        env:
          VERSION: ${{ steps.next-version.outputs.version }}
